version: "3.9"

services:
  snipdox:
    build: .
    container_name: snipdox
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
